Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"

  # This is just to make the download a little bit faster. Ignore this. 
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.network "forwarded_port", guest: 4001, host: 4001
  config.vm.network "forwarded_port", guest: 5001, host: 5001

  # Sync Folders. Everthing you put in the current direcory will be availabe inside the VM in the directory /vagrant.
  # Similarly, everything you put in the folder shared will be availabe inside de the VM in the directory /shared.
  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder "../shared", "/shared"

  # Stop some firewall and security configuration so that you don't have to worry it this and makes things easier. Ignore this.
  config.vm.provision "shell",
    inline: "sudo systemctl stop firewalld; sudo systemctl disable firewalld"

  # This runs the script you need to modify. 
  config.vm.provision :shell, path: "bootstrap.sh"

end
